### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by ghost** [wzpan/QtEVM#1]
What exactly is the license?

Can people use it under LGPLv3 or not? If indeed the license is LGPLv3 you should also include the [GPLv3](http://www.gnu.org/licenses/gpl-3.0.txt) since the LGPLv3 only lists the differences between the two.

If you have restriction like "non-commercial research purposes only." it's not LGPL anymore. This would also make it not "open source" like you advertised in your Hacker News [post](https://news.ycombinator.com/item?id=11525335). You should read the ["open source" definition](https://opensource.org/osd).

**Comment by wzpan** [comment]
You are right. I did misinterpret the definition of open source. Will remove the LGPL license.

**Comment by wzpan** [comment]
I've modified the license and restrict to non-commercial only. Close this issue. Any questions else, please reopen this issue. ;-)

**Comment by ghost** [comment]
> I've modified the license and restrict to non-commercial only. Close this issue. Any questions else, please reopen this issue. ;-)

Only restricting won't do anything. You have to also grant the rights. By default people aren't allowed to do anything with your work.

**Comment by ghost** [comment]
What is your reasoning for not wanting to release QtEVM under a free license?

E: under these terms "because I made it" is not really a good answer since if that's the reason you might as well not release it at all since no none is going to benefit from it.

E2: Remember that people aren't even allowed to modify, compile or run your program thus you cannot even use them as free testers or bugfixers.

**Comment by wzpan** [comment]
As I said, this work is use for academic purpose. People are allow to use the code for research. It's very useful for students who want to study EVM and would like play with OpenCV rather than Matlab.

I won't release it under a free license because I don't have the right to. The original algorithm is pattern protected.

**Comment by ghost** [comment]
> As I said, this work is use for academic purpose. People are allow to use the code for research. It's very useful for students who want to study EVM and would like to do something with the help of OpenCV.

Is studying legally classified as "research"? You need to be really careful with your license wording.

> I won't release it under a free license because I don't have the right to. The original algorithm is pattern protected. 

Patent?

Can I see the patent?

**Comment by wzpan** [comment]
> Is studying legally classified as "research"? You need to be really careful with your license wording.

I don't mean it. Studying is just an example.

> Patent? Can I see the patent?

Yes. Thank you for correct it. See the Codes and Binaries section of the [EVM website](http://people.csail.mit.edu/mrub/evm/) .

**Comment by ghost** [comment]
> I don't mean it. Studying is just an example.

If it's not legally classified as research then it's a good example of what isn't allowed.

You need to include the [whole license](http://people.csail.mit.edu/mrub/evm/code/LICENSE.pdf). That one line alone is too vague and doesn't give anyone right to do anything.

**Comment by wzpan** [comment]
Wow I haven't noticed that document. Good job! 👍
