### ISSUE TITLE
color magnification

### ISSUE THREAD

**Issue by iziadmohamed** [wzpan/QtEVM#3]
when i press color magnification some processing happen then an error appear

**Comment by wzpan** [comment]
please give me more details on your system environments.

**Comment by botrosfawzy** [comment]
Opencv 3.2.0
Qt 5.8.0
![error](https://cloud.githubusercontent.com/assets/25537099/22763933/33049870-ee70-11e6-8804-cd1db7ad6d00.png)

**Comment by wzpan** [comment]
Looks like you built it under VS. For some weird reason it dosen't work quite well for Qt + VS + OpenCV. It's suggested that you run it under Linux. Or try the pre-compiled version: https://github.com/wzpan/QtEVM/releases

**Comment by wzpan** [comment]
It's been a long time without any responds, so close this issue. Any further questions, welcome to reopen it.
